### ISSUE TITLE
Inconsistent image transparency with hosted images 

### ISSUE THREAD

**Issue by misslivirose** [mozilla/reticulum#241] opened 2019-10-08 18:48 UTC
I was guessing this was a reticulum bug because the issue happens outside of the Hubs room render, but if I'm wrong, I can move this over to the main Hubs repo. 

**Issue:** 
Transparency issues are present in reticulum image, but not when the image is taken and rendered in Hubs.

Image from the camera, taken and as it appears in Hubs: 
![image](https://user-images.githubusercontent.com/4313320/66423829-4fe6da80-e9c1-11e9-8962-ccbddc11cf63.png)

Image Link opened in the browser: 
![image](https://user-images.githubusercontent.com/4313320/66423865-5d9c6000-e9c1-11e9-8fc5-a89e36f9407b.png)

Link to reticulum hosted image: https://uploads-prod.reticulum.io/files/087edc54-57a4-4802-811f-a9a6b420e992.png?token=f1b1edac1f01598aa06e73d3a6c5efab

**Comment by blairmacintyre** [comment] 2019-10-08 18:49
FWIW, we've seen all kinds of issues with transparency (weird edges, etc.) but noticed recently that Safari wasn't rendering transparency at all.  Not sure if it's related.

**Comment by brianpeiris** [comment] 2022-09-12 00:09
I believe this bug was caused by the in-world camera in Hubs. If an object in the room had some transparency to it, it would cause photos taken with the camera to have incorrect transparent pixels.
As far as I can tell, this bug has been fixed in the hubs client code.

**Closed by brianpeiris** 2022-09-12 00:09 UTC
