### ISSUE TITLE
(EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2

### ISSUE THREAD

**Issue by ruliusuifeng** [mozilla/reticulum#512] opened 2021-07-16 03:19 UTC
run "iex -S mix phx.server" then :
[info] Application ret exited: Ret.Application.start(:normal, []) returned an error: shutdown: failed to start child: RetWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2
        ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2Server
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function :pg2.create/1 is undefined or private
                    (kernel 8.0.1) :pg2.create({:phx, Ret.PubSub})
                    (phoenix_pubsub 1.1.2) lib/phoenix/pubsub/pg2_server.ex:43: Phoenix.PubSub.PG2Server.init/1
                    (stdlib 3.15.1) gen_server.erl:423: :gen_server.init_it/2
                    (stdlib 3.15.1) gen_server.erl:390: :gen_server.init_it/6
                    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by nicokruger** [comment] 2021-08-19 11:59
did you find anything on resolving this @ruliusuifeng ?

**Comment by brianpeiris** [comment] 2021-09-02 17:08
This might be caused by using a newer version of Erlang than we support. I'd suggest using Erlang 23 or 22 for the time being.

**Comment by albirrkarim** [comment] 2022-02-02 07:17
I got same error

![image](https://user-images.githubusercontent.com/29292018/152110391-b3cc3ea9-cce8-4d7d-bfde-317e026137db.png)

**Closed** 2022-09-12 00:47 UTC
